[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "text/javascript"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "text/css"

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' https://vhsxydevxstvqmatvnge.supabase.co https://polvsbcamskaycejxlmf.supabase.co https://psymmxfknulxspcbvqmr.supabase.co; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.google.com/recaptcha/ https://www.gstatic.com/recaptcha/ data: blob:; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com data:; frame-src 'self' https://www.google.com/recaptcha/ https://www.gstatic.com/recaptcha/; img-src 'self' data: https: http:; media-src 'self' blob: https://polvsbcamskaycejxlmf.supabase.co https://psymmxfknulxspcbvqmr.supabase.co; connect-src 'self' https://vhsxydevxstvqmatvnge.supabase.co https://polvsbcamskaycejxlmf.supabase.co https://psymmxfknulxspcbvqmr.supabase.co https://www.google.com/recaptcha/ https://isendora.app.n8n.cloud/; object-src 'none'; worker-src 'self' blob:; child-src 'self' blob:;"

[build]
  command = "npm run build"
  publish = "dist"
  
[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200